#spring:
#  application:
#    name: business-service
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#  profiles:
#    active: test
#---
#
#spring:
#  profiles: businessService1
#server:
#  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9090/eureka

---

#spring:
#  profiles: businessService2
#server:
#  port: 8081
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9090/eureka


#添加日志埋点输出配置
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
