#server:
#  port: 9090
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:9090/eureka

spring:
  application:
    name: eureka-service
---

spring:
  profiles: eurekaService1
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

---

#spring:
#  profiles: eurekaService2
#server:
#  port: 9091
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9090/eureka