spring:
  application:
    name: hystrix-service

server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

turbine:
  #要监控的微服务列表,多个用,分隔
  appConfig: index-service
  clusterNameExpression: "'default'"